### ISSUE TITLE
sandbox attach 进程后，应用端报 url 错误

### ISSUE THREAD

**Issue by xipfs** [vivo/MoonBox#11]
2023-03-02T10:05:22.407+08:00  INFO 14054 --- [Attach Listener] c.v.j.s.moonbox.module.MoonboxModule     : module on loaded, id: moonbox, version: 1.0.0, mode: ATTACH
2023-03-02T10:05:22.407+08:00  INFO 14054 --- [Attach Listener] c.v.j.s.moonbox.module.MoonboxModule     : moonbox module onActive...
2023-03-02T10:05:22.409+08:00  INFO 14054 --- [eartbeat-pool-1] c.v.j.s.m.module.MoonboxHeartbeatTask    : moonbox repeater is starting! heartbeat ignored! taskRunId=null
Exception in thread "moonbox-thread-pool-1" java.lang.IllegalArgumentException: unexpected url: null/api/agent/getConfig?_r=1&taskRunId=null&ip=127.0.1.1
        at okhttp3.Request$Builder.url(Request.java:143)
        at com.alibaba.jvm.sandbox.repeater.plugin.core.utils.HttpUtil.doGet(HttpUtil.java:73)
        at com.alibaba.jvm.sandbox.repeater.plugin.core.impl.api.MoonboxConfigManager.pullConfig(MoonboxConfigManager.java:48)
        at com.vivo.jvm.sandbox.moonbox.module.MoonboxModule.lambda$loadCompleted$0(MoonboxModule.java:171)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-02T10:05:32.409+08:00  INFO 14054 --- [eartbeat-pool-1] c.v.j.s.m.module.MoonboxHeartbeatTask    : moonbox repeater is starting! heartbeat ignored! taskRunId=null
2023-03-02T10:05:42.410+08:00  INFO 14054 --- [eartbeat-pool-1] c.v.j.s.m.module.MoonboxHeartbeatTask    : moonbox repeater is starting! heartbeat ignored! taskRunId=null
2023-03-02T10:05:52.410+08:00  INFO 14054 --- [eartbeat-pool-1] c.v.j.s.m.module.MoonboxHeartbeatTask    : moonbox repeater is starting! heartbeat

**Comment by yananliuyanjiang** [comment]
这里的attach缺少了 -T 参数，我们改造了原生sandbox.sh脚本需要传递参数，参数会在startServerAgent 和startLocalAgent地方输出

**Comment by yananliuyanjiang** [comment]
> 

com.vivo.internet.moonbox.service.console.util.AgentUtil#getAgentStartConfig在这里计算了 -T 参数，逻辑很简单

**Comment by zhyn456128** [comment]
<img width="931" height="555" alt="Image" src="https://github.com/user-attachments/assets/eea14281-79bf-4884-b781-abf9cc2ca4b1" />
这种就是成功了吗？？？
