### ISSUE TITLE
启动录制任务后，日志报错Provider sun.tools.attach.LinuxAttachProvider not found 

### ISSUE THREAD

**Issue by jimingzhi** [vivo/MoonBox#36]
具体报错详情
java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.LinuxAttachProvider not found at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593) 
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219) 
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) 
at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) 
at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) 
at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) 
at jdk.attach/com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:260) 
at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:200) 
at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:59) 
at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20) 
at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)

这个是什么情况？

**Comment by jimingzhi** [comment]
已经知道了，jdk版本问题。。。版本太高了，没有tool.jar
