### ISSUE TITLE
centos上docker部署失败

### ISSUE THREAD

**Issue by haohongbin** [vivo/MoonBox#47]
error:
moonbox-elasticsearch    | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
moonbox-elasticsearch    | Error: Could not create the Java Virtual Machine.
moonbox-elasticsearch    | Error: A fatal exception has occurred. Program will exit.
moonbox-elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)
moonbox-elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
moonbox-elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
moonbox-elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
moonbox-elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)

**Comment by chenjianpengok** [comment]
去docker文件下把elasticsearch目录复读写权限试试？

**Comment by MrZbb** [comment]
同样的报错

**Comment by ASwordCold** [comment]
把docker目录下的elasticsearch目录权限修改为777，就可以了。
另外elasticsearch外挂目录需要手动新建一下，也同样赋予777的权限。

**Comment by chow-q** [comment]
after this ,it work
 1000  mkdir -R /usr/share/elasticsearch/data
 1001  mkdir -r /usr/share/elasticsearch/data
 1002  mkdir -p /usr/share/elasticsearch/data
 1003  mkdir -p /usr/share/elasticsearch/logs
 1004  mkdir -p /usr/share/elasticsearch/plugins
 1005  chmod 777 -R /usr/share/elasticsearch
